server/checkstyle.xml, server/src/main/java/de/uftos/controller/StudentController.java, server/src/main/java/de/uftos/controller/StudentGroupController.java, server/src/main/java/de/uftos/controller/SubjectController.java, server/src/main/java/de/uftos/entities/Student.java, server/src/main/java/de/uftos/entities/StudentGroup.java, server/src/main/java/de/uftos/entities/Subject.java, server/src/main/java/de/uftos/repositories/StudentRepository.java, server/src/main/java/de/uftos/repositories/SubjectRepository.java, server/src/main/java/de/uftos/services/StudentService.java, server/src/main/java/de/uftos/services/SubjectService.java
- Editor -> Code Style -> Java -> cogwheel near scheme ->  Import Scheme -> Checkstyle configuration
- Tools -> Checkstyle -> Scan Scope: Only Java Sources (including tests)
- Tools -> Checkstyle: Enable Google Checks in the table
=> feat: formatting rules

server/pom.xml
`/swagger-ui/index.html` for the WebUI and `/v3/api-docs` for json
=> add open api with swagger

server/src/main/java/de/uftos/entities/ConstraintArgument.java, server/src/main/java/de/uftos/entities/ConstraintInstance.java, server/src/main/java/de/uftos/entities/ConstraintParameter.java, server/src/main/java/de/uftos/entities/ConstraintSignature.java, server/src/main/java/de/uftos/entities/Curriculum.java, server/src/main/java/de/uftos/entities/Grade.java, server/src/main/java/de/uftos/entities/Lesson.java, server/src/main/java/de/uftos/entities/LessonsCount.java, server/src/main/java/de/uftos/entities/Room.java, server/src/main/java/de/uftos/entities/Student.java, server/src/main/java/de/uftos/entities/StudentGroup.java, server/src/main/java/de/uftos/entities/Subject.java, server/src/main/java/de/uftos/entities/Tag.java, server/src/main/java/de/uftos/entities/Teacher.java, server/src/main/java/de/uftos/entities/Timeslot.java, server/src/main/java/de/uftos/entities/Timetable.java
To remove orphaned tables the DB volume should be deleted (`docker compose down -v db`)
=> fix: database relations

server/src/main/java/de/uftos/controller/ServerController.java, uftos-openapi-specs.json, web/src/lib/sdk/fetch-client.ts
Of course I forgot something...
=> fix: rename timetable metadata endpoints

server/src/main/java/de/uftos/dto/SubjectRequestDto.java, server/src/main/java/de/uftos/repositories/database/SubjectRepository.java, server/src/main/java/de/uftos/services/SubjectService.java, server/src/test/java/de/uftos/e2e/SubjectsTest.java, server/src/test/java/de/uftos/services/SubjectServiceTests.java
Written unit tests and e2e tests for the subject service and subject endpoint
=> feat: subject service

server/src/main/java/de/uftos/repositories/ucdl/parser/DefinitionParser.java, server/src/main/java/de/uftos/services/ConstraintInstanceService.java
Added semantics check for "==" and "!=".
Fixed/added semantics check for "element in set".
Fixed quantifier.
=> Parser Update

server/src/main/java/de/uftos/controller/GradeController.java, server/src/main/java/de/uftos/controller/SubjectController.java, server/src/main/java/de/uftos/controller/TagController.java, server/src/main/java/de/uftos/repositories/database/GradeRepository.java, server/src/main/java/de/uftos/repositories/database/SubjectRepository.java, server/src/main/java/de/uftos/repositories/database/TagRepository.java, server/src/main/java/de/uftos/services/GradeService.java, server/src/main/java/de/uftos/services/SubjectService.java, server/src/main/java/de/uftos/services/TagService.java, server/src/test/java/de/uftos/e2e/SubjectsTest.java, uftos-openapi-specs.json, web/src/lib/sdk/fetch-client.ts, web/src/routes/admin/(resources)/subjects/+page.svelte, web/src/routes/admin/(resources)/tags/+page.svelte
Removes the pagination from
- tags,
- subjects and
- grades.
=> refactor: remove pagination

server/src/main/java/de/uftos/dto/ConstraintInstancesResponseDto.java, server/src/test/java/de/uftos/services/ConstraintInstanceServiceTest.java, uftos-openapi-specs.json, web/src/lib/sdk/fetch-client.ts
* Cleaned up the ConstraintInstancesResponseDto
* Checkstyle
* Updated open api
* Update server/src/main/java/de/uftos/dto/ConstraintInstancesResponseDto.java
---------
=> fix: open api sort (#175)

server/src/main/java/de/uftos/repositories/ucdl/UcdlRepository.java, server/src/main/java/de/uftos/repositories/ucdl/UcdlRepositoryImpl.java
Including a method to parse any String.
=> String parser

server/ucdl/ucdl.yml
Defined predefined constraints in ucdl.yml.
=> Add predefined constrains.

server/src/main/java/de/uftos/controller/UcdlEditorController.java, server/src/main/java/de/uftos/dto/ucdl/ParsingResponse.java, server/src/main/java/de/uftos/repositories/ucdl/UcdlRepositoryImpl.java, server/src/main/java/de/uftos/services/UcdlEditorService.java, uftos-openapi-specs.json, web/.prettierignore, web/package-lock.json, web/package.json, web/src/lib/components/editor.svelte, web/src/lib/elements/ui/sonner/index.ts, web/src/lib/elements/ui/sonner/sonner.svelte, web/src/lib/sdk/fetch-client.ts, web/src/routes/+layout.svelte, web/src/routes/admin/editor/+page.svelte
=> feat: editor

server/src/main/java/de/uftos/repositories/ucdl/parser/UcdlParser.java
=> Fixing problem with lessons as valid parameters.

server/src/main/java/de/uftos/services/UcdlEditorService.java
=> Fixing problem with faulty consistency-check.

server/src/main/java/de/uftos/repositories/ucdl/parser/UcdlParser.java
=> Fixing problem with null pointers.

server/pom.xml, server/src/main/java/de/uftos/repositories/ucdl/UcdlRepository.java, server/src/main/java/de/uftos/repositories/ucdl/UcdlRepositoryImpl.java, server/src/main/java/de/uftos/repositories/ucdl/parser/UcdlParser.java, server/src/main/java/de/uftos/services/UcdlEditorService.java
Replacing jackson with snakeyaml and fixing problem with duplicate definitions being accepted.
closes #236
=> Replacing jackson with snakeyaml.

server/src/main/java/de/uftos/repositories/ucdl/parser/DefinitionParser.java, server/src/main/java/de/uftos/repositories/ucdl/parser/UcdlParser.java
=> Illegal legal code fix

server/src/main/java/de/uftos/repositories/ucdl/parser/DefinitionParser.java
=> Fixed missing catch for TokenMgrError.

server/src/main/java/de/uftos/services/UcdlEditorService.java, server/src/test/java/de/uftos/services/RoomServiceTests.java
=> Fixing signature updates.

server/src/main/java/de/uftos/controller/UcdlEditorController.java, server/src/main/java/de/uftos/repositories/ucdl/UcdlRepository.java, server/src/main/java/de/uftos/repositories/ucdl/UcdlRepositoryImpl.java, server/src/main/java/de/uftos/services/UcdlEditorService.java, uftos-openapi-specs.json, web/src/lib/components/editor.svelte, web/src/lib/sdk/fetch-client.ts
=> feat: expose and use default ucdl file

web/src/lib/elements/ui/dataTable/data-table-actions.svelte, web/src/lib/elements/ui/dataTable/data-table.svelte
Additionally row selection now shows total amount of elements.
=> Fix: Selected rows when deleting from action menu.

web/src/lib/components/ui/link-bar/link-bar.svelte, web/src/lib/elements/ui/navbar/navbar.svelte
=> Chore: update navbar

server/src/main/java/de/uftos/services/CurriculumService.java, server/src/test/java/de/uftos/services/CurriculumServiceTests.java, server/src/test/java/de/uftos/services/StudentServiceTest.java
=> Fixed lesson count removal on curriculum update.

web/src/lib/components/editor.svelte
=> fix: upload to editor

server/src/main/java/de/uftos/UftosApplication.java, uftos-openapi-specs.json, web/playwright.config.ts, web/src/lib/sdk/fetch-client.ts, web/tests/admin.e2e-spec.ts, web/tests/constraints.e2e-spec.ts, web/tests/curriculum.e2e-spec.ts, web/tests/grade.e2e-spec.ts, web/tests/room.e2e-spec.ts, web/tests/settings.e2e-spec.ts, web/tests/student-group.e2e-spec.ts, web/tests/students.e2e-spec.ts, web/tests/subject.e2e-spec.ts, web/tests/tag.e2e-spec.ts, web/tests/teacher.e2e-spec.ts
=> fix: deployment

web/src/hooks.server.ts, web/src/lib/utils/server.ts, web/src/routes/+page.ts, web/src/routes/admin/(resources)/curriculums/+page.ts, web/src/routes/admin/(resources)/grades/+page.ts, web/src/routes/admin/(resources)/grades/[id]/+page.ts, web/src/routes/admin/(resources)/rooms/+page.ts, web/src/routes/admin/(resources)/rooms/[id]/+page.ts, web/src/routes/admin/(resources)/studentGroups/+page.ts, web/src/routes/admin/(resources)/studentGroups/[id]/+page.ts, web/src/routes/admin/(resources)/students/+page.ts, web/src/routes/admin/(resources)/students/[id]/+page.ts, web/src/routes/admin/(resources)/subjects/+page.ts, web/src/routes/admin/(resources)/subjects/[id]/+page.ts, web/src/routes/admin/(resources)/tags/+page.ts, web/src/routes/admin/(resources)/tags/[id]/+page.ts, web/src/routes/admin/(resources)/teachers/+page.ts, web/src/routes/admin/(resources)/teachers/[id]/+page.ts, web/src/routes/admin/+page.ts, web/src/routes/admin/settings/+page.ts, web/src/routes/timetable/[type]/[[id]]/+page.ts
=> fix: web requests (cors!!!!)
